### ISSUE TITLE
got it up and running

### ISSUE THREAD

**Issue by ghost** [khalahan/NamecoinToBind#3]
got everything up and running great, but I had to manually remove these names from the zone in order to get named running. should we create some kind of filter in namescan.php for these or ....

db.namecoin.bit:17: -.bit: bad owner name (check-names)
db.namecoin.bit:18: *.-.bit: bad owner name (check-names)
db.namecoin.bit:30: --.bit: bad owner name (check-names)
db.namecoin.bit:31: *.--.bit: bad owner name (check-names)
db.namecoin.bit:100: **.bit: bad owner name (check-names)
db.namecoin.bit:101: *.**.bit: bad owner name (check-names)
db.namecoin.bit:209: n-.bit: bad owner name (check-names)
db.namecoin.bit:210: n-.bit: bad owner name (check-names)
db.namecoin.bit:211: www.n-.bit: bad owner name (check-names)
db.namecoin.bit:1905: exa-.bit: bad owner name (check-names)
db.namecoin.bit:1906: exa-.bit: bad owner name (check-names)
db.namecoin.bit:1907: www.exa-.bit: bad owner name (check-names)
db.namecoin.bit:2767: non-.bit: bad owner name (check-names)
db.namecoin.bit:2768: non-.bit: bad owner name (check-names)
db.namecoin.bit:2769: www.non-.bit: bad owner name (check-names)
db.namecoin.bit:2968: pre-.bit: bad owner name (check-names)
db.namecoin.bit:2969: pre-.bit: bad owner name (check-names)
db.namecoin.bit:2970: www.pre-.bit: bad owner name (check-names)
db.namecoin.bit:4069: giga-.bit: bad owner name (check-names)
db.namecoin.bit:4070: giga-.bit: bad owner name (check-names)
db.namecoin.bit:4071: www.giga-.bit: bad owner name (check-names)
db.namecoin.bit:4574: post-.bit: bad owner name (check-names)
db.namecoin.bit:4575: post-.bit: bad owner name (check-names)
db.namecoin.bit:4576: www.post-.bit: bad owner name (check-names)
db.namecoin.bit:12818: the_seven.bit: bad owner name (check-names)
db.namecoin.bit:12819: *.the_seven.bit: bad owner name (check-names)
dns_master_load: db.namecoin.bit:13043: bittacular.bit: CNAME and other data

**Comment by khalahan** [comment]
Fixed in commit 2a9bcf1c7911cddaaaa254db476a85f5c31487ff & tag v3.0.5
Thanks for reporting.
